# Site settings
site: blog
title: Blog Personal de Carlos Ardila
keywords: cardila, blog
description: >-
  Blog Personal de Carlos Ardila
lang: en-US
timezone:  America/Bogota
repo: https://github.com/onepase/Ephesus # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  blogcardila

# Author settings
author:
  name: Carlos Ardila
  bio: Computer Engineer, Father, Audiophile, Boardgamer, Geek 
  picture: assets/images/profile.jpg 
  github: chardila # github username
  twitter: cardila # twitter username
  facebook: cardila # facebook username
  instagram: cardila01 # instagram username
  youtube: https://www.youtube.com/channel/UCdmbolTV_xXQIwdiYd9D8UQ # youtube username
  linkedin: cardila # linkedin username
  email: blog@cardila.com # email adress


# URL settings
url: "https://code.cardila.com/blogpersonal" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
